Update tpl_shopping_cart_default.php
lat9/ZCA-Bootstrap-Template-BETA- pull request #403
Opened 2024-06-28 14:17 UTC by retched

Hides the Update Cell in the Shopping Cart unless the option `SHOW_SHOPPING_CART_UPDATE` is specifically set to `Next to each Qty Box` or `Both Next to each Qty Box and Below all Products`.

2024-06-28 14:21 UTC, retched commented
Running the shopping card through an evaluation tool suggested that to comply with WCAG standard 1.3.1 a `<TH>` tag shouldn't be empty or contain images with no alt text.

So I hide that column that would contain the update button UNLESS it is explicitly set in the Admin dashboard. As well as change the last column, the total column, to a regular `<TD>` instead of a `<TH>`.

2024-06-28 15:19 UTC, retched commented
It was a suggestion that <th>'s shouldn't be empty, even with a non-breaking space, for accessibility. To quote the guideline I found:

https://webaim.org/techniques/tables/data#th
Table headers should never be empty. This is particularly of concern for the top-left cell of some tables

I'm not sure how stringent that is though.

========
Respectfully submitted,


Paul L. Williams III
________________________________
From: lat9 ***@***.***>
Sent: Friday, June 28, 2024 11:11 AM
To: lat9/ZCA-Bootstrap-Template ***@***.***>
Cc: Paul Williams ***@***.***>; Author ***@***.***>
Subject: Re: [lat9/ZCA-Bootstrap-Template] Update tpl_shopping_cart_default.php (PR #403)


Thanks for this. I'll review later this weekend. Why the change to td instead of th?

—
Reply to this email directly, view it on GitHub<https://github.com/lat9/ZCA-Bootstrap-Template/pull/403#issuecomment-2197150733>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAL75NFPTD6U5IG7RIOXL53ZJV4KPAVCNFSM6AAAAABKB7Z4RSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCOJXGE2TANZTGM>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-06-28 15:26 UTC, drbyte commented
One way we handle the "no empty header cell" elsewhere in Zen Cart is to simply give it a header of "Action". 
And often make that text aria-only.

2024-06-28 15:33 UTC, retched commented
I didn't even consider that as a possibility. I can make a similar change in another commit.

2024-07-08 15:10 UTC, retched commented
I reverted the empty cells to a `<th>` but gave each column an aria-label header with an empty cell. I also added two language definitions to `lang.zca_bootstrap_common.php` for this purpose.

2024-07-08 18:39 UTC, lat9 requested changes
Resolve those couple of indentation 'issues' and it's good to go.

2024-07-08 18:39 UTC, lat9 commented on includes/templates/bootstrap/templates/tpl_shopping_cart_default.php
> +                <?php if (SHOW_SHOPPING_CART_UPDATE == 1 || SHOW_SHOPPING_CART_UPDATE == 3) { ?><th scope="col" class="d-none d-sm-table-cell" id="cartTableDisplay-qtyUpdateHeading"><span aria-label=
I'm bit bit more persnickety and don't like the 'inline' PHP conditionals.  Please indent the `<php` conditional to line up with its parent and render the HTML portion separately (also indented to match the other `th` elements).

2024-07-08 18:39 UTC, lat9 commented on includes/templates/bootstrap/templates/tpl_shopping_cart_default.php
> +                <?php if (SHOW_SHOPPING_CART_UPDATE == 1 || SHOW_SHOPPING_CART_UPDATE == 3) { ?><td class="qtyUpdateCell text-center d-none d-sm-table-cell"><?php echo (!empty($product['buttonUpdate'
Ditto for the `<td>`.

2024-07-08 23:25 UTC, retched commented
Should be done. Also went ahead and adjusted the quantity field to render the HTML aligned within the `<td>` itself too.
![image](https://github.com/lat9/ZCA-Bootstrap-Template/assets/1572532/551b5dc9-e1ef-4efa-ad4c-fa18651909ca)

2024-07-08 23:37 UTC, retched commented
Squashed the three commits to make things easier to follow.

2024-07-09 13:56 UTC, lat9 approved these changes

2024-07-09 13:58 UTC, merged

2024-07-09 14:08 UTC, lat9 commented
Tie this PR to the associated issue, #410.